import { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Rubik } from "next/font/google";
import { Toaster } from "sonner";
import { Suspense } from "react";
import Loading from "./loading";
import "./globals.css";
import ReduxProvider from "@/providers/redux-provider";

const rubik = Rubik({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

const ibmPlex = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Warqa Store",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body
        className={`${rubik.className} ${ibmPlex.className} antialiased relative overflow-x-hidden`}
      >
        <Suspense fallback={<Loading />}>
          <ReduxProvider>
            {children}
            <Toaster />
          </ReduxProvider>
        </Suspense>
      </body>
    </html>
  );
}
